version: "3.8"

services:
  backend:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    command: /app/scripts/start-dev.sh
    depends_on:
      - app_db

  app_db:
    image: postgres:15.3
    container_name: app_db
    hostname: app_db
    env_file:
      - .env
    ports:
      - "5432:5432"